[project]
name = "policy-compliance-guardian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.13.1",
]

[tool.uv.workspace]
members = [
    "src/mcp-server",
]
